### ISSUE TITLE
Cannot compile wrf-teb (gfortran: fatal error: Killed signal terminated program f951)

### ISSUE THREAD

**Issue by adjebbar** [TEB-model/wrf-teb#5]
After executing

```
BUILD_TYPE=Release
BUILD_MODE=dmpar
cd wrf-teb
mkdir -p build
cd build
cmake -GNinja -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
-DMODE=$BUILD_MODE \
-DCMAKE_INSTALL_PREFIX=install ..
ninja install
```

ninja terminates with the following error:

```


FAILED: frame/CMakeFiles/frame.dir/module_configure.F.o frame/mod/module_configure.mod frame/mod/module_irr_diag.mod frame/mod/module_scalar_tables.mod
/usr/bin/gfortran -I../frame -I../inc -Iinc -I../frame/../arch -I../frame/../external/ioapi_share -I/home/cons/WORK/WRF_model/Build_WRF/LIBRARIES/mpich/include -Iframe/mod -Iexternal/esmf_time_f90/mod -Iexternal/io_int/mod -cpp -fconvert=big-endian -frecord-marker=4 -ffree-line-length-none -DNONSTANDARD_SYSTEM_SUBR -O3 -Jframe/mod -fPIC -ffree-form -fpreprocessed -c frame/CMakeFiles/frame.dir/module_configure.F-pp.f -o frame/CMakeFiles/frame.dir/module_configure.F.o
../frame/module_configure.F:330:14:

330 | ! the grid id's. In the grid_config_rec the domain-specific information
| 1
Warning: missing terminating ' character
../frame/module_configure.F:436:35:

436 | ! developers and are still in user's namelists.
| 1
Warning: missing terminating ' character
gfortran: fatal error: Killed signal terminated program f951
compilation terminated.
ninja: build stopped: subcommand failed.
```

**Comment by dmey** [comment]
@adjebbar what are your system info and version? OS, Fortran compiler, CMake, Ninja

**Comment by adjebbar** [comment]
Ubuntu 20.04 focal
GNU Fortran (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
cmake version 3.16.3
ninja --version 1.10.0

**Comment by adjebbar** [comment]
Ubuntu 20.04 focal
GNU Fortran (Ubuntu 9.3.0-17ubuntu120.04) 9.3.0
gcc (Ubuntu 9.3.0-17ubuntu120.04) 9.3.0
cmake version 3.16.3
ninja --version 1.10.0

**Comment by dmey** [comment]
It may be a memory issue with the Fortran compiler? How much RAM do you have installed?

**Comment by adjebbar** [comment]
My laptop RAM is 8 GO

**Comment by dmey** [comment]
That's probably it. You can try in Debug mode and one core for now i.e.
```
BUILD_TYPE=Debug
cmake -GNinja -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
-DMODE=$BUILD_MODE \
-DCMAKE_INSTALL_PREFIX=install ..
ninja install -j 1
```

if it compiles retry in Release. Note that WRF simulations require high memory and CPU.

**Comment by adjebbar** [comment]
Thanks, Yes it woks now !!!
Should I do the same for WPS with Cmake?

**Comment by dmey** [comment]
Good. For WPS, you can download the experimental precompiled binaries. See `wps-cmake-4.1.0-basic_nesting-dmpar-x64-linux-release.tar.xz` under `Assets` at https://github.com/WRF-CMake/wps/releases for Linux.
